### ISSUE TITLE
tier 5 zombies slowly reduce to 0 spawning

### ISSUE THREAD

**Issue by smash223** [TehNut/Soul-Shards-The-Old-Ways#29]
#### Issue Description:
mopack author said to report here 

#### What happens:

 im having an issue.  i have a tier 5 zombie shard.  place it in the soul cage and turn it on.  if the first cycle of spawns spawn a chicken jockey, the next run the total number of spawned zombies is reduced by the number of jockeys.  ie...

30 zombies spawn 5 of witch are jockey.. next spawn cycle 25 zombies spawn with 5 being jockeys.. next cycle 20 zombies spawn...this continues until nothing spawns.  occasionaly a chicken jockey spawns with an invisible rider. after spawns stop

ive broken spawner moved to new area loged out.  the only thing to fix it is server restart.  also if i use a diffrent shard for instance a tier 5 skelly shard works perfect.

#### What you expected to happen:
exspected to maintain 30 mobs for blood magic use

#### Steps to reproduce:

1. tier 5 zombie shard in soul cage under bloodmagic well of suffering
2. using ender i/o redstone conduit for on/off
3. random things advanced item collector underneath collecting drops 
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: soulshard-tow-1.10.2-2.6.1-41.jar
- Minecraft: running minecraft 1.10.2  modpack avant 3
- Forge:  forge-12.18.1.2063

**Comment by TehNut** [comment]
Update.
